@startuml
!pragma layout smetana

object Bruger
object Parkering
object Zoner
object Kort
object Bil
object Betaling

Bruger --> Bil  : has-a
Bruger --> Kort  : has-a
Bil --> Parkering
Parkering --> Zoner : has-a
Zoner --> Betaling : has-a




@enduml