@startuml

!pragma layout smetana

actor "User" as U

rectangle "Streaming Service System" {
  usecase "UC0: StartApplication" as UC0
  usecase "UC1: CreateUser" as UC1
  usecase "UC2: LogIn" as UC2
  usecase "UC3: findAvailableParking" as UC3
  usecase "UC4: addLicense" as UC4
  usecase "UC5: Payment" as UC5
  usecase "UC6: EndParking" as UC6

  usecase "MainMenuMap" as M

  }

U --> UC0

UC0 --> UC1
UC0 --> UC2

UC2 --> M
M --> UC3
UC1 --> UC4
UC4 --> M
UC3 --> UC5
UC5 --> UC6



@enduml